### ISSUE TITLE
miscalculating width in beamer

### ISSUE THREAD

**Issue by johannesbottcher** [cgnieder/tasks#11]
From https://tex.stackexchange.com/questions/334763/tasks-package-items-are-in-two-line-with-4-columns-and-4-items 

>It seems that tasks cannot compute the right width for the tasks with beamer when aspectratio=169 is in effect. - egreg Oct 19 '16 at 14:05

```
\documentclass[aspectratio=169]{beamer}
\usetheme{Berkeley}
\usepackage{tasks}
\begin{document}
\begin{frame}
\transwipe
1.Which one you want to choose?
\begin{tasks}[counter-format=tsk[A].,debug=true](4)
\task A
\task B
\task C
\task D
\end{tasks}
\end{frame}
\end{document}
```

**Comment by cgnieder** [comment]
This probably  the same problem as issues #10 and #12. Seems to be fixed now.
