### ISSUE TITLE
Error when using more than 26 tasks with alphabetic counter 

### ISSUE THREAD

**Issue by mikepierce** [cgnieder/tasks#16]
I'm using the setting `\settasks{counter-format=(tsk[a])}` to use the task labels (a), (b), (c), ...

But if I have more that 26 tasks, so it would have to go past (z), I get an error

    ./main.tex:251: Undefined control sequence.
    \GenericError  ...                                
                                                        #4  \errhelp \@err@     ...
    l.251         \end{tasks} 

I'm not sure *what* should come after (z), but I can't imagine it should result in a compile error.

**Comment by cgnieder** [comment]
The following also results in an error:
```latex
\documentclass{article}
\begin{document}

\newcounter{foo}
\setcounter{foo}{27}
\alph{foo}

\end{document}
```

**Comment by cgnieder** [comment]
The syntax for setting the counter format will change in the next version but an error in this case cannot be prevented…
