### ISSUE TITLE
possibility to add multiple choice lists again?

### ISSUE THREAD

**Issue by maphy-psd** [cgnieder/tasks#19]
In the new version v1.0 the multiple choice style are removed. So my template are broken (it's no problem, i can fix that). Although xsim has the support for multiple choice questions, but not completely like tasks.

So..my questions ist: can you add the multiple choice style to tasks again (or add it to xsim)?

I think that the multiple choice style is useful, especially when you don't use xsim.

Thank you for your work. We use your packages (xsim&tasks) for our exercises in our school (hhgym.de) and love it!

P.S. Why you have removed the multiple choice lists in tasks?

**Comment by cgnieder** [comment]
There are so many different kind of multiple choice questions (e.g. https://tex.stackexchange.com/questions/444102/) and thematically they don't really belong to the `tasks` package.

And it is really easy to define something suitable:

```latex
\documentclass{article}
\usepackage{tasks}
\usepackage{fontawesome}

\NewTasksEnvironment[label=\faSquareO]{choices}[\choice]
\newcommand\correct{\faCheckSquareO}

\begin{document}

\begin{choices}(4)
  \choice A
  \choice B
  \choice C
  \choice D
\end{choices}

\begin{choices}(4)
  \choice A
  \choice B
  \choice[\correct] C
  \choice D
\end{choices}

\end{document}
```
![image](https://user-images.githubusercontent.com/2248538/67147209-27998e80-f293-11e9-9394-68188bc13fff.png)

**Comment by Sk1nk** [comment]
I would like to second that request. I am fine with defining a new class like suggested 
> \NewTasksEnvironment[label=\faSquareO]{choices}[\choice](4)
> \newcommand\correct{\faCheckSquareO}
but this one limits the me to having 4 choices next to each other. Creating a new test I had to define 3 different classes for 
5 next to each other, 3 next to each other and all of them vertically, where before I just had to change the number within the round brackets. 

This, in my eyes, is a step back.

**Comment by cgnieder** [comment]
> but this one limits the me to having 4 choices next to each other. 

It doesn't. You can still use

```latex
\begin{choices}(2)
  \choice A
  \choice B
  \choice C
  \choice D
\end{choices}
```
or any other column number you want with said definition. My suggestion just sets an arbitrary 4 default columns as an example.

> This, in my eyes, is a step back.

Again it isn't. Earlier versions of `tasks` did the same kind of definition. They simply used 1 instead of 4 default columns. In the new version this would be
```latex
\NewTasksEnvironment[label=\faSquareO]{choices}[\choice]
```
or
```latex
\NewTasksEnvironment[label=\faSquareO]{choices}[\choice](1)
```
which are equivalent definitions.
