### ISSUE TITLE
Issue with recent version of tasks and numbering of task items

### ISSUE THREAD

**Issue by the-fourth-man** [cgnieder/tasks#23]
As detailed in [https://tex.stackexchange.com/questions/584249/issue-with-recent-version-of-tasks-and-numbering](url)

The behaviour of `\task[]` has changed, it now produces an unlabeled task, however it increases a step in the enumeration.

```latex
\documentclass{article}

\usepackage{tasks}
    \settasks{
    %debug,
    style=enumerate,
    label-format=\bfseries,
    label-align=right,
    label-width=21pt,
    label-offset=6pt,
    item-indent=27pt,
    column-sep=0.5em,}

\begin{document}

\begin{tasks}(2)
\task[] Not numbered
\task[] Not numbered
\task This used to be numbered 1
\task[] Not numbered
\task This used to be numbered 2
\task[] Not numbered
\task This used to be numbered 3
\task[] Not numbered
\end{tasks}

\end{document}
```

![image](https://user-images.githubusercontent.com/2248538/108606558-02eb8480-73bb-11eb-8306-d662e310154d.png)
**

**Comment by cgnieder** [comment]
Thanks for the report. Fixed.

**Comment by noboevbo** [comment]
I just noticed the change above as I was working on 1.3 and recently switched to 1.3a. I actually use the mechanism of the continuing counter to replace unchecked boxes with checked boxes in front of the task numbers in xsim solutions. Would it be possible to add a bool flag option "continueCounterOnCustomLabels" or similar for this behaviour and include it in the check at line 565 (v. 1.3a)?
