### ISSUE TITLE
Add a possibility to count custom labels

### ISSUE THREAD

**Issue by noboevbo** [cgnieder/tasks#25]
I am referring to issue #23 which fixed the behavior of counting custom labels. I use custom labels to replace empty checkboxes with checked checkboxes in xsim solutions. Here's the code snippet I use for my multiple choice questions:
```LaTeX
% Multiple choice
\NewTasksEnvironment[label=\faSquareO~\Alph*), label-width=27pt]{choices}[\choice]
\newcommand*\correct{\IfInsideSolutionTF{\StrSubstitute{\thetask}{\faSquareO}{\faCheckSquareO}}{\thetask}}
```
So, for example I have tasks A) B) C) D) from which B and C are correct (`\choice[\correct]`). With the current version 1.3a this results in the labeling: A) A) A) B) because B and C would get a custom label.

To allow such a use case I suggest adding the option "count-custom-labels". I forked the project and added this option. Is this something you would like to see in the package / do you accept pull requests? Link to the commit: [Commit 0a5265d](https://github.com/noboevbo/tasks/commit/0a5265dfc312df249d6709306ee97438b2728b63). Note that I just started getting into the expl3 syntax, the code would be cleaner if there's a possibility to combine the two if statements using logical operators?!

**Comment by cgnieder** [comment]
It looks like you're missing a `\refstepcounter`, see also issue #24.
