### ISSUE TITLE
Overlapping of lines in the task environment

### ISSUE THREAD

**Issue by DouglasJ52** [cgnieder/tasks#26]
I use the tasks package to write a book where I have a lot of enums. The experience with the package has been very good so far.

The case is that I changed my OS from Mint to Ubuntu, 20.04.3 LTS, 64 bits, GNOME 3.36.8 and now the new compilations produce from the task environment an output in which the rows of the lists overlap each other, I want say: they are mounted on top of each other.

I have searched for a solution in Google and I have not found it.

**Comment by cgnieder** [comment]
Hi. Without an minimal example file that lets me reproduce your issue I won't be able to help.
