### ISSUE TITLE
Vertical skip seems not accurate

### ISSUE THREAD

**Issue by jiaopjie** [cgnieder/tasks#27]
When set vertical skips `before-skip`, `after-skip` and `after-item-skip` to be `0pt`, these skips seem not precisely `0pt`.
Compared with this, when load the package `enumitem` with option `nosep`, the vertical skips between items of `enumerate` are the same with normal main text.

The following is my code.
```
\documentclass{article}
\usepackage{enumitem,tasks}
\setlist{nosep,leftmargin=*}
\settasks{before-skip=0pt,after-skip=0pt,after-item-skip=0pt}
\begin{document}
\parindent0pt
\fbox{some text}\\
\fbox{some text}
\begin{enumerate}
  \item \fbox{item~1}
  \item \fbox{item~2}
\end{enumerate}
\fbox{some text}
\begin{tasks}
  \task \fbox{item~1}
  \task \fbox{item~2}
\end{tasks}
\fbox{some text}
\end{document}
```
Below is the result.
![Dingtalk_20211123211408](https://user-images.githubusercontent.com/9783188/143031418-17ea8b39-a5e3-4419-ad5c-b42baa544e5b.jpg)

**Comment by cgnieder** [comment]
Thanks, fixed in the next release.
