### ISSUE TITLE
weird error with simple input file

### ISSUE THREAD

**Issue by carlodri** [cgnieder/tasks#7]
This simple input file:

```latex
\documentclass[11pt, a4paper]{article}
\usepackage{exsheets}
\usepackage[detect-all=true]{siunitx}
\usepackage[version=3]{mhchem}

\begin{document}
\begin{question}{2}
	$c_\ce{Cu} = \SI{386}{J/(kg.K)}$
\end{question}
\end{document}
```

gives me [this](https://gist.github.com/carlodri/b6aef2b676f85b04f3fa) weird error, that I honestly can't figure out.

It turns out that the following modification `$c_{\ce{Cu}} = \SI{386}{J/(kg.K)}$` instead compiles fine, probably pointing out to some quarrel between `tasks.sty` and `mhchem`?

Another clue: this line `$c_\text{Cu} = \SI{386}{J/(kg.K)}$` also compiles fine.

It is not so crucial, but I'm reporting as a reference in case someone gets crazy on it like me before isolating the culprit...

**Comment by cgnieder** [comment]
This has nothing to do with tasks. I don't know why this is happening but actually both `c_\ce{Cu}` and `c_\text{Cu}` are wrong LaTeX syntax despite the fact that the second one is working. This syntax is bound to give errors in both cases and the proper syntax is to use braces just like you've detected.

BTW: this MWE gives the same error:

```latex
\documentclass{article}
\usepackage[version=3]{mhchem}
\begin{document}

$c_\ce{Cu}$

\end{document}
```
Further reference: http://tex.stackexchange.com/questions/239301/mhchem-macro-in-subscript

**Comment by carlodri** [comment]
Oops, sorry, you're correct! Thanks for the clarification!
