### ISSUE TITLE
Add an option for switching the entire tasks environment to math mode.

### ISSUE THREAD

**Issue by student-sx** [cgnieder/tasks#8]
On of the motivations of creating the tasks packages seems to be (from the manual):

> The reason for the tasks environment is an unwritten agreement in German maths textbooks
> (exspecially in (junior) high school textbooks) to organize exercises in columns counting horizontally > rather than vertically. That is what tasks primarily is for. If you don’t need this feature
> you’re better off using traditional LATEX lists and the enumitem package for customization.

Now such exercises often consist of only math formulas (for example calculating some integrals or derivatives) without text. Then you have to enter mathmode for every task. With regard to the quoted aim of the package, I think it would be a good idea to have an option such that the whole task environment operates in mathmode (similar as you can have matrices of math nodes in tikz). 

Here is an example of a similar environment called brqalign, which was created by David Carlisle in response of one of my questions:

http://tex.stackexchange.com/a/51543/4011

**Comment by cgnieder** [comment]
Nice idea. This should be easy to implement. I'm thinking of a more general option which lets the user apply an arbitrary formatting to an item. This would cover math-mode then.

**Comment by cgnieder** [comment]
```latex
\documentclass{article}
\usepackage{tasks}[2016/05/02]

\settasks{
  item-format = \ensuremath
}

\begin{document}

\begin{tasks}(4)
  \task y + 4x
  \task \sin(x)
  \task \int e^x \,dx
  \task a^2 + b^2
\end{tasks}

\end{document}
```

![tasks](https://cloud.githubusercontent.com/assets/2248538/14952636/42081488-1062-11e6-991b-a40e9fad9c92.png)
