### ISSUE TITLE
\newpage doesn't work inside tasks environment

### ISSUE THREAD

**Issue by uzsolt** [cgnieder/tasks#9]
As the title says can't break a page inside `tasks`:
```
\documentclass{article}
\usepackage{tasks}
\begin{document}
\begin{tasks}
  \task Foo
  \newpage
  \task Bar
\end{tasks}
\end{document}

```

Expected result: two pages.

**Comment by cgnieder** [comment]
It's true that this doesn't work and it will never work. The manual even says the following in section 3.1 (Basics):

>  A first difference: there is no pagebreak possible inside an item but only between items.

The reason is that items are collected in boxes and typeset as such. Trying to use `\newpage` here is essentially the same as trying to use `\mbox{\newpage}`

**Comment by uzsolt** [comment]
Ah, understand.
But there is a workaround (works for me): `...\end{tasks}\newpage\begin{tasks}[resume=true]...`
Maybe it's worth to share this tip in the documentation :)
